# Generated by Django 5.1.4 on 2025-03-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence_plus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerequest',
            name='work_type',
            field=models.CharField(choices=[('Work from Home', 'Work from Home'), ('Field Work', 'Field Work')], max_length=20),
        ),
    ]
