# Generated by Django 5.1.4 on 2025-03-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence_plus', '0002_alter_attendancerequest_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerequest',
            name='work_type',
            field=models.CharField(max_length=20),
        ),
    ]
