# Generated by Django 5.1.4 on 2025-03-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence_plus', '0003_alter_attendancerequest_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerequest',
            name='work_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
