# Generated by Django 5.1.4 on 2025-03-23 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence_plus', '0004_alter_attendancerequest_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='leave_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presence_plus.leavetransaction'),
        ),
    ]
