# Generated by Django 5.1.7 on 2025-03-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence_plus', '0005_alter_leavebalance_leave_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeshiftassignment',
            name='shift_roster',
        ),
        migrations.DeleteModel(
            name='ShiftRoster',
        ),
    ]
